project:
  type: website
  output-dir: ../docs

website:
  title: "Python for Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Day One"
        menu:
          - text: "Session One: Numbers, Booleans, and Strings"
            href: day_1_session_1.qmd
          - text: "Session Two: Collections"
            href: day_1_session_2.qmd
          - text: "Session Three: Iteration, Functions, and Classes"
            href: day_1_session_3.qmd
      - text: "Day Two"
        menu:
          - text: "Session One: Packages and NumPy"
            href: day_2_session_1.qmd
          - text: "Session Two: Pandas"
            href: day_2_session_2.qmd
          - text: "Session Three: Visualization and Statistical Modelling"
            href: day_2_session_3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right

execute:
  freeze: auto
